name: CI

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  RUSTFLAGS: -Dwarnings

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        rust:
          - "stable"
          - "nightly"
          - "1.36" # MSRV

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true
          profile: minimal
          components: clippy, rustfmt

      # hack for making tests work, since criterion requires a high msrv
      - name: ignore benchmark
        if: ${{ matrix.rust == '1.36' }}
        run: sed -i 24d Cargo.toml

      - name: test
        run: |
          if [ ${{ matrix.rust }} != "1.36" ]
          then cargo test --all-features --workspace
          else cargo test --all-features --all
          fi

      - name: fmt
        if: ${{ matrix.rust == 'stable' }}
        run: cargo fmt -- --check

      - name: clippy
        run: cargo clippy --all-features
